version: '2'
services:
  xbee:
    image: efeo/dfw:tcp_xbee_bridge
    network_mode: host
    privileged: true
    command: xbee_bridge --ip 127.0.0.1
  control:
    extends:
      file: ../services/control/control.yml
      service: control
  mavros:
    extends:
      file: ../services/mavros_xbee/mavros.yml
      service: mavros
    volumes:
      - ../../logs:/root/.ros/log:rw
      - ./mavros_xbee_local.launch:/root/catkin_ws/src/mav_control/launch/mavros_xbee.launch:ro  
    env_file:
      - ./mavros_0.env
