version: '2'
services:
  control:
    extends:
      file: ../services/control/control.yml
      service: control
  viz:
    extends:
      file: ../services/viz/viz.yml
      service: viz
    command: roslaunch erle_models viz.launch ns:=copter_0
  viz1:
    extends:
      file: ../services/viz/viz.yml
      service: viz
    command: roslaunch erle_models viz.launch ns:=copter_1
  viz2:
    extends:
      file: ../services/viz/viz.yml
      service: viz
    command: roslaunch erle_models viz.launch ns:=copter_2
  viz-rover:
    extends:
      file: ../services/viz/viz.yml
      service: viz
    command: roslaunch erle_models viz.launch type:=rover.urdf ns:=rover_0
