version: '2'
services:
  control:
    extends:
      file: ../services/control/control.yml
      service: control
  viz:
    extends:
      file: ../services/viz/viz.yml
      service: viz
  viz-rover:
    extends:
      file: ../services/viz/viz.yml
      service: viz
    command: roslaunch erle_models viz.launch type:=rover.urdf ns:=rover_0
