version: '2'
services:
  merger:
    network_mode: host
    image: jeguzzi/df:mavros_merger
    volumes:
      - ../logs:/root/.ros/log:rw
    command: roslaunch mavros_merger main.launch drones:=false controllers:=false
    # i.e. take the param published from the df bridge
    env_file:
      - ../ros.env
  fanout:
    extends:
      file: ../services/fanout/fanout.yml
      service: fanout
    env_file:
      - ./mavros_0.env
  mavproxy:
    extends:
      file: ../services/fanout/fanout.yml
      service: mavproxy
    env_file:
      - ./mavros_0.env
