name: TestDF
# reload: true
map: map_pozyx2.xml
cached: false
drones:
   - &d0
      kind: rover
      id: rover_0
      xbee: r1
controllers:
   -
      hostname: demo
      position: [100, 100]
      ip: 192.168.201.4
   -
      hostname: node21
      position: [800, 100]
      ip: 192.168.201.24
      range: POLYGON ((0 0, 1000 0, 1000 600, 0 600, 0 0))
   -
      hostname: node22
      position: [200, 800]
      ip: 192.168.201.24
      range: POLYGON ((0 400, 1000 400, 1000 1000, 0 1000, 0 400))
planners:
   rover:
      layer: 'L2'
      cache: True
      tol: 0.01
anchors:
   positions:
       - [0x602c, 1300, 9630, 1190]
       - [0x6031, 1300, -270, 2630]
       - [0x600c, 9380, -270, 2500]
       - [0x602d, 9380, 9630, 2260]
       - [0x6024, 9612, 4049, 2000]
       - [0x6034, -250, 5890, 2600]
optitrack:
   crs:
      y: 466.6
      x: 537.3
      alpha: 90
