version: '2'
services:
  redis:
    image: redis
    command: /redis.conf
    volumes:
      - /tmp
      - ./redis.conf:/redis.conf:ro
      - ../data:/data:rw
  server:
    image: jeguzzi/df:server
    volumes:
      - ./server.cfg:/app/config/server.cfg:ro
      - ./worlds:/app/worlds:ro
    volumes_from:
     - redis
    depends_on:
     - redis
    environment:
      DF_FLASK_CONFIG: /app/config/server.cfg
      PYTHONPATH : /app/src
    entrypoint: ''
    command: /bin/bash -c 'cd /app; gunicorn -w 1 -k gevent -b unix:/tmp/gunicorn.sock --timeout 900 --log-level DEBUG dronefly_flask_server:app'
  nginx:
    image: nginx
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
     - redis
    depends_on:
     - server
    ports:
    - "80:8000"
  bridge:
    network_mode: host
    image: jeguzzi/df:ros_bridge
    volumes:
      - ../logs:/root/.ros/log:rw
      - ./bridge.launch:/root/catkin_ws/src/df_bridge/launch/bridge.launch:ro
    volumes_from:
     - server
    depends_on:
     - redis
    environment:
      - "PYTHONPATH=/app/src"
    command: roslaunch df_bridge bridge.launch world:=/app/worlds/footbots
    env_file:
      - ../ros.env
  monitor:
    network_mode: host
    privileged: true
    image: jeguzzi/df:docker-ui
    volumes:
      - ../logs:/root/.ros/log:rw
      - /var/run/docker.sock:/var/run/docker.sock
    command: roslaunch docker_ui monitor.launch
    environment:
     - "ifaces=['en0', 'en5']"
    ports:
     - 8085:8085
     - 9090:9090
    env_file:
      - ../ros.env
  planner:
    network_mode: host
    image: jeguzzi/df:ros_bridge
    volumes_from:
      - server
    volumes:
      - ../logs:/root/.ros/log:rw
      - ./planner.launch:/root/catkin_ws/src/sync_df/launch/planner.launch:ro
    command: roslaunch sync_df planner.launch
    env_file:
      - ../ros.env
    environment:
      - "PYTHONPATH=/app/src"
  control:
    network_mode: host
    image: jeguzzi/df:mav_control
    volumes:
      - ../logs:/root/.ros/log:rw
      - ./controller.launch:/root/catkin_ws/src/mav_control/launch/controller.launch:ro
    command: roslaunch mav_control controller.launch
    env_file:
      - ../ros.env
  optitrack_odom:
    network_mode: host
    image: jeguzzi/ros:optitrack
    volumes:
      - ../logs:/root/.ros/log:rw
      - ./optitrack.launch:/root/catkin_ws/src/optitrack_odom/launch/optitrack.launch:ro
    command: roslaunch optitrack2odom optitrack.launch
    env_file:
      - ../ros.env
  lcm:
    network_mode: host
    image: efeo/ros:optitrack_lcm_bridge
    volumes:
      - ../logs:/root/.ros/log:rw
    command: roslaunch optitrack_lcm_bridge main.launch
    env_file:
      - ../ros.env
  footbot_bridge:
    network_mode: host
    image: efeo/ros:footbot_control
    volumes:
      - ../logs:/root/.ros/log:rw
    command: rosrun footbot_tools footbot_control.py _robots:=[55,66]
    env_file:
      - ../ros.env
