version: '2'
services:
  mavros:
    net: host
    image: jeguzzi/df:mav_control
    env_file:
      - ../ros.env
      - ./mavros.env
    volumes:
      - ./logs:/root/.ros/log:rw
    command: roslaunch mav_control mavros_xbee.launch
