version: '2'
services:
 mavros:
    network_mode: host
    image: jeguzzi/df:mav_control
    env_file:
      - ../../ros.env
    volumes:
      - .../../logs:/root/.ros/log:rw
    command: roslaunch mav_control mavros_xbee.launch
