version: '2'
services:
  fanout:
    network_mode: host
    image: jeguzzi/df:mavros_merger
    volumes:
      - ../../logs:/root/.ros/log:rw
    command: roslaunch mavros_merger fanout.launch in=$in out=$out ns=$ns
    env_file:
      - ../../ros.env
  mavproxy:
    network_mode: host
    image: jeguzzi/df:mavproxy
    command: mavproxy.py --master=:$out --out=:$in --daemon
